### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by buibui8buibui** [Panzer-Jack/ChatGPT_VITS_For_QQ-Rob#1]
Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      setup.py:26: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        _CYTHON_INSTALLED = ver >= LooseVersion(min_cython_ver)
      Traceback (most recent call last):
        File "H:\ChengXU\Anaconda\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "H:\ChengXU\Anaconda\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "H:\ChengXU\Anaconda\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\saki\AppData\Local\Temp\pip-build-env-l9jw4xu_\overlay\Lib\site-packages\setuptools\build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "C:\Users\saki\AppData\Local\Temp\pip-build-env-l9jw4xu_\overlay\Lib\site-packages\setuptools\build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "C:\Users\saki\AppData\Local\Temp\pip-build-env-l9jw4xu_\overlay\Lib\site-packages\setuptools\build_meta.py", line 267, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\saki\AppData\Local\Temp\pip-build-env-l9jw4xu_\overlay\Lib\site-packages\setuptools\build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 153, in <module>
        File "H:\ChengXU\Anaconda\lib\subprocess.py", line 505, in run
          with Popen(*popenargs, **kwargs) as process:
        File "H:\ChengXU\Anaconda\lib\subprocess.py", line 951, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "H:\ChengXU\Anaconda\lib\subprocess.py", line 1420, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] 系统找不到指定的文件。
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by Panzer-Jack** [comment]
这个看起来像 安装 requirement 的时候出现的问题，你能具体描述一下 你安装的步骤吗？

**Comment by Panzer-Jack** [comment]
你安装依赖库所用的 python版本号是多少？

**Comment by buibui8buibui** [comment]
用隔壁https://github.com/MuBai-He/ChatWaifu-marai，
里的Anaconda方式模拟的环境。不知道哪里出错了。

**Comment by Panzer-Jack** [comment]
> 你安装依赖库所用的 python版本号是多少？

我看了下，可能你的Python版本号太高，你试试用Python3.8的版本装依赖库试试

**Comment by Panzer-Jack** [comment]
> 用隔壁[https://github.com/MuBai-He/ChatWaifu-marai，](https://github.com/MuBai-He/ChatWaifu-marai%EF%BC%8C) 里的Anaconda方式模拟的环境。不知道哪里出错了。

我看了下那个库的版本是3.10，你的Python版本号可能太高了 有的依赖库版本匹配不了，你试试用Python3.8的版本装依赖库试试

**Comment by buibui8buibui** [comment]
好几个GPT账号都G了，感觉只能指望GML了，话说有办法支持sovits4.0模型吗？租A40跑了几个模型不想浪费了。

**Comment by Panzer-Jack** [comment]
> 好几个GPT账号都G了，感觉只能指望GML了，话说有办法支持sovits4.0模型吗？租A40跑了几个模型不想浪费了。

我弄了张P40 等之后就去做glm本地化。sovits  没玩过，之后有空去看看
